### ISSUE TITLE
update bolognese gem

### ISSUE THREAD

**Issue by kjgarza** [datacite/orcid_client#4]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fyx7)

**Comment by mfenner** [comment]
Please link the associated code changes.

**Comment by kjgarza** [comment]
update bolognese and verion of gem https://github.com/datacite/orcid_client/commit/1f885556d833f0fe1b498c3440c5e95c219e3e11
